import streamlit as st
import pandas as pd
import json
import main

# Page configuration for a professional dashboard layout
st.set_page_config(page_title="FinOps Agent Dashboard", layout="wide")

# State Management: Required to handle the Human-in-the-Loop workflow
# Ensures the UI doesn't reset when re-rendering after LLM execution
if 'decision_pending' not in st.session_state:
    st.session_state.decision_pending = False
if 'decision_data' not in st.session_state:
    st.session_state.decision_data = None

st.title("Cloud FinOps Autonomous Agent")
st.markdown("Infrastructure monitoring and HITL-approved Terraform optimization platform.")

# -----------------------------------------------------------------------------
# Section 1: Current Infrastructure Overview
# -----------------------------------------------------------------------------
try:
    with open("metrics.json", "r") as f:
        data = json.load(f)
    df = pd.DataFrame(data["resources"])
    total_cost = df['cost_per_month_usd'].sum()
    
    st.subheader("Current Infrastructure State")
    st.dataframe(
        df[["resource_name", "environment", "resource_type", "current_type", "cpu_usage_avg_percent", "cost_per_month_usd"]], 
        use_container_width=True
    )
    st.metric(label="Current Monthly Cost", value=f"${total_cost:.2f}")

except Exception as e:
    st.error(f"Failed to load metrics data: {e}")

st.markdown("---")
st.subheader("Autonomous FinOps Engine")

# -----------------------------------------------------------------------------
# Section 2: Analysis Phase (Agent analyzes but does NOT execute)
# -----------------------------------------------------------------------------
if not st.session_state.decision_pending:
    if st.button("Run Analysis Engine"):
        with st.spinner("Fetching infrastructure state and generating optimization strategy..."):
            try:
                # Trigger the LLM analysis via backend module
                result = main.analyze_infrastructure()
                
                # Store results in session state to pause the workflow for human review
                st.session_state.decision_data = result
                st.session_state.decision_pending = True
                st.rerun() # Force UI refresh to show the approval screen
            except Exception as e:
                st.error(f"Analysis process failed: {e}")

# -----------------------------------------------------------------------------
# Section 3: Execution Phase (Human-in-the-Loop Approval)
# -----------------------------------------------------------------------------
if st.session_state.decision_pending and st.session_state.decision_data:
    st.warning("Action Required: Optimization strategy generated. Pending manual approval before infrastructure modification.")
    
    decision = st.session_state.decision_data
    
    # Financial impact metrics
    col1, col2 = st.columns(2)
    with col1:
        st.metric(label="Estimated Monthly Savings", value=f"${decision['estimated_savings_usd']:.2f}")
    with col2:
        new_cost = total_cost - float(decision['estimated_savings_usd'])
        st.metric(label="Projected Monthly Cost", value=f"${new_cost:.2f}", delta=f"-${decision['estimated_savings_usd']:.2f}", delta_color="inverse")
    
    # Technical change log (Markdown table generated by LLM)
    with st.expander("Review Proposed Changes", expanded=True):
        st.markdown(decision['mr_description'])

    # Action buttons for execution or rejection
    c1, c2 = st.columns([1, 5])
    with c1:
        if st.button("Approve & Execute", type="primary"):
            with st.spinner("Applying changes and generating Merge Request..."):
                try:
                    # Push approved changes to remote repository
                    mr_url = main.apply_changes(decision)
                    st.success("Infrastructure modification successful.")
                    st.markdown(f"**Merge Request:** [View in GitLab]({mr_url})")
                    
                    # Reset state machine after successful execution
                    st.session_state.decision_pending = False
                    st.session_state.decision_data = None
                except Exception as e:
                    st.error(f"Execution failed: {e}")
    with c2:
        if st.button("Reject & Discard"):
            # Reset state machine without executing changes
            st.session_state.decision_pending = False
            st.session_state.decision_data = None
            st.rerun()